version: '3.8'
networks:
  rentalsbackend:
services:

  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: npm run start:dev 
    env_file:
      - ./apps/gateway/.env
    depends_on:
      - mysql-db
      - auth
      # - invoices
      # - houses
    #   - users
    #   - payments
    #   - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    networks:
      - rentalsbackend
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    depends_on:
      - mysql-db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8080:8080'
    networks:
      - rentalsbackend
  # invoices:
  #   build:
  #     context: .
  #     dockerfile: ./apps/invoices/Dockerfile
  #     target: development
  #   command: npm run start:dev invoices
  #   env_file:
  #     - ./apps/invoices/.env
  #   depends_on:
  #     - rabbitmq
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - '7070:7070'
  # users:
  #   build:
  #     context: .
  #     dockerfile: ./apps/users/Dockerfile
  #     target: development
  #   command: npm run start:dev invoices
  #   env_file:
  #     - ./apps/users/.env
  #   depends_on:
  #     - rabbitmq
  #     - auth
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - '5550:5550'
  # houses:
  #   build:
  #     context: .
  #     dockerfile: ./apps/houses/Dockerfile
  #     target: development
  #   command: npm run start:dev houses
  #   env_file:
  #     - ./apps/houses/.env
  #   depends_on:
  #     - auth
  #     - rabbitmq
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - '9090:9090'
  # payments:
  #   build:
  #     context: .
  #     dockerfile: ./apps/payments/Dockerfile
  #     target: development
  #   command: npm run start:dev payments
  #   env_file:
  #     - ./apps/payments/.env
  #   depends_on:
  #     - auth
  #     - rabbitmq
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - '5050:5050'
  # rabbitmq:
  #   image: rabbitmq
  #   ports:
  #     - '5672:5672'
  mysql-db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    # volumes:
    #   - my-db:/var/lib/mysql
    networks:
      - rentalsbackend

  
  
  
