apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - port: 4001
  type: ClusterIP

---
kind: Service
apiVersion: v1
metadata:
  name: houses
spec:
  selector:
    app: houses
  ports:
    - port: 4002
  type: ClusterIP

---
kind: Service
apiVersion: v1
metadata:
  name: invoices
spec:
  selector:
    app: invoices
  ports:
    - port: 4003
  type: ClusterIP

---
kind: Service
apiVersion: v1
metadata:
  name: payments
spec:
  selector:
    app: payments
  ports:
    - port: 4004
  type: ClusterIP

---
kind: Service
apiVersion: v1
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 4000
      nodePort: 30000
  type: NodePort