export const LandlordMock = {
  title: 2,
  userId: 1,
  accounts_accounts_landlordTolandlord: {
    acc_name: 'sdasda',
    acc_num: 4234234,
    accounts: 1,
    bank_branch: 'dssd',
    bank_name: 'sdfasd',
    landlord: 1,
  },
  landlord: 1,
  name: 'wewer',
  paybill: 21122,
  property_property_landlordTolandlord: {
    uid: 'onebedroomProperty',
    agent: 1,
    caretaker: 1,
    landlord: 1,
    location: 'Donhome',
    name: 'Savanah Estate',
    property: 1,
    rental_unit: 2,
  },
};
